### ISSUE TITLE
Have the next slide slightly appear? 

### ISSUE THREAD

**Issue by skimaharvey** [rcaferati/react-awesome-slider#167]
Hello there,

I love the library bu I was wondering if there were anyway to have the next slide slightly appear?

Thank you for your help/tips

**Comment by trolit** [comment]
Hello :) If by "slightly appear" you mean how fast next slide appears over the previous one please look at the <a href="https://caferati.me/demo/react-awesome-slider/images">live demo</a>. There you will find on the right side property called `slider-transition-duration`. Play with it with different values to see if that is what you want to achieve. If it does, you will have to overwrite that property using raw CSS or create your own copy of slider styles in SCSS and modify it from there. Alternatively you could also create your own instance of component that you've chosen(e.g. autoplay.js) and adjust to your needs(how changing slides behaves).

**Comment by skimaharvey** [comment]
Thank you very much by the detailed reponse however I wasnt clear enough. What I meant next slide appears a little bit on the side. Like the example below.
<img width="1113" alt="Screen Shot 2021-02-04 at 13 39 10" src="https://user-images.githubusercontent.com/64636974/106893949-94d26c80-66ee-11eb-89f5-7e214d64ae5c.png">

**Comment by trolit** [comment]
Thanks for the details! As far as I am concerned repo consider only single slide examples. If you would like to achieve that effect you definietly would have to make some changes to the slider behaviour. I'm assuming that within the example you shown above by "next slide appears a little bit on the side" you mean only that next image fragment(not the text titled "A New Era of Glamour"). I've thought about one tricky idea which you could try.. If we look at e.g. <a href="https://github.com/rcaferati/react-awesome-slider/blob/master/demo/examples/example/autoplay.js">autoplay.js</a> you will find function called `renderSlides` which looks like this:
```js
  const renderSlides = () => {
    return slides.map(slide => {
      return (
        <div
          key={slide.src}
          style={{ backgroundColor: slide.backgroundColor }}
          data-src={slide.src}
        />
      );
    });
  };
```
If you would like the user to see the incoming slide you would have to change that function first so instead of single slide it returns two(current one and the next one). Map function allows to refer to the next index e.g. <a href="https://stackoverflow.com/questions/49462751/how-to-get-the-next-element-on-map-function">stackoverflow</a>(remember about case when referencing last image from slider to point to the first index not index + 1). This way each "slide" would have current one and the next one and you would only have to create appropiate styles for that incoming slide fragment by using for e.g. <a href="https://www.w3schools.com/cssref/pr_pos_clip.asp">clip</a> property to crop image and then position it :) 

I didn't try it but if it sounds promising feel free to try it :)

Alternatively you can look after ready solutions that instantly allows to have multiple slides like <a href="https://github.com/YIZHUANG/react-multi-carousel">react-multi-carousel</a> from YIZHUANG(click <a href="https://react-multi-carousel.now.sh/">here</a> for preview, I've thought about the example on the bottom of the page)

PS:
If you decide to try with react-awesome-slider, consider using `clip-path`(<a href="https://css-tricks.com/clipping-masking-css/#the-new-clip-path">link</a>) instead of clip mentioned above since it's deprecated (oops 😄 ). It also would require some polishing to get rid of incoming slide fragment repetition that was cropped on previous slide.

**Comment by skimaharvey** [comment]
This is great! Thank you very much for your detailed answer. Might go with the multi-carousel library
