### ISSUE TITLE
Loading Bar disappears

### ISSUE THREAD

**Issue by GodspeedChloe** [rcaferati/react-awesome-slider#187]
Loading bar disappears after you make it all the way to the end of the gallery and reset back to the first image.  This can even be observed on the demo page [here](https://caferati.me/demo/react-awesome-slider).

**Comment by trolit** [comment]
Hello @GodspeedChloe. The behavior you described works as intended cause it's "preloading" indicator. When you "ask" for the image first time, it's being "cached". Instead of showing you empty slider area until it's fully loaded, you see that bar that informs about next image first time processing status. The next time you ask for the same image you won't experience indicator cause there is no need to wait for image to be loaded since it can be retrieved instantly.

**Comment by GodspeedChloe** [comment]
Ah, I see.  Thanks for clearing that up.
